### PR TITLE
Pause/Resume/Remove Functionality

### PR DESCRIPTION
**Pull request by omareg94**
Add Pause/Resume/Remove hotkey functionality.
Test Example is included.

### CODE REVIEW

**Review by evilC — CHANGES_REQUESTED** [review]
Toggle generally implies passing no parameters and inverting on/off state
Suggest that we rename Toggle to "SetState"

**Review by omareg94 — COMMENTED** [review]
Done changing "Toggle" to "SetState".

**Comment by evilC** [comment]
Sorry for putting another one on you, only really had a chance to skim it the other day.
Would recommend renaming `PauseKey`, `ResumeKey`, `RemoveKey` to something else - using the word `Key` does not seem to sit right as THM can be used for mouse or joystick buttons - so replace `Key` with `Button` I guess?
Please remove the example code from `TapHoldManager.ahk` - either put it in the documentation (`Readme.md`) or add it as one or more separate files. I am happy to do the documentation though, so if you like you can just completely remove it

**Comment by omareg94** [comment]
@evilC 
It's okay I'm happy to any edits :) and thanks for following up and trying to make code enhanced
I think word `Hotkey` seems to be more accurate than word `button`. What do you think?
`PauseKey`, `ResumeKey`, and `RemoveKey` are now replaced with `PauseHotkey`, `ResumeHotkey`, and `RemoveHotkey`.
Also I moved examples to separate file named `SimpleExample2.ahk`

**Comment by evilC** [comment]
Yeah, that sounds OK

**Pull request merged**
